version: 0.2
env:
  secrets-manager:
    LOGIN: sonarapitoken:sonartoken
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - java -version
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.0.2311-linux.zip
      - unzip ./sonar-scanner-cli-4.6.0.2311-linux.zip
      - export PATH=$PATH:./sonar-scanner-4.6.0.2311-linux/bin/
  build:
    commands:    
      - sonar-scanner -Dsonar.login=$LOGIN -Dsonar.host.url=$HOST -Dsonar.projectKey=$Project -Dsonar.organization=$Organization -Dsonar.scm.disabled=true
      - |
        status="PENDING";
        while [ "${status}" != "SUCCESS" ]; do
          if [ "${status}" = "FAILED" ] || [ $"{status}" = "CANCELLED" ]; then
            echo Status is Failed/Cancelled
            exit 1;
          fi
          curl --silent https://sonarcloud.io/api/qualitygates/project_status?projectKey=$Project >result.json
          status=$(jq -r '.projectStatus.status' result.json)
          echo ${status}
          sleep 5;
        done
      - cat result.json
      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] || [ $(jq -r '.projectStatus.status' result.json) = WARN ]; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi
artifacts:
    files: '**/*' 